### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.any')

### ISSUE THREAD

**Issue by wmcbain** [stoffern/react-native-image-cropper#49] opened 2017-12-07 18:35 UTC
<img width="376" alt="screen shot 2017-12-07 at 1 24 11 pm" src="https://user-images.githubusercontent.com/7080654/33731720-14c36448-db52-11e7-81cf-1ef1c132bf23.png">

This seems to be coming from the `gl-react-image` dependency, using react native 0.50.0+

**Comment by stoffern** [comment] 2017-12-07 20:44
do you have a file called `Image.js` and do you use `React.PropTypes` ?

**Comment by wkoutre** [comment] 2017-12-07 23:37
This is coming from src/Image.js and lib/Image.js.

Adding `prop-types` as a peerDependency, importing it into the two files mentioned above, and changing all `React.PropTypes` to `PropTypes` fixes the issue.

I can submit a PR if you want, but there's not much to making the changes I've mentioned above.

**Comment by stoffern** [comment] 2017-12-08 07:44
Those files does not exist in the `gl-react-image` repo.
@wkoutre if you know of any bugs in other repos, i suggest you create PRs and help out the community!

**Comment by wkoutre** [comment] 2017-12-08 15:49
@stoffern I was going to make a PR on `gl-react-image` but it’s not the same version being installed when running `yarn install gl-react-native` as required by `react-native-image-croppers`.

If you create a dummy project and install `gl-react-native`, you’ll see what I mean. The `src` and `lib` folders are in the the root of the `gl-react-image` project that also gets installed.

I’ve made a quick script to to replace the correct files locally, but I’ll have more time this weekend to make a PR.

**Comment by stoffern** [comment] 2017-12-08 17:31
it uses the latest..
https://github.com/stoffern/react-native-image-cropper/blob/master/package.json#L33

**Comment by wkoutre** [comment] 2017-12-08 20:13
@stoffern Please do the following:

1. `react-native init TestProj && cd TestProj`
2. `yarn add react-native-image-cropper gl-react gl-react-native`
3. `open node_modules/gl-react-image/`

In the directories that opens, you'll see `lib/` and `src/` directories.

src/Image.js:

```
import GL from "gl-react";
import React, {PropTypes} from "react";
import rectCrop from "rect-crop";
import rectClamp from "rect-clamp";

...

propTypes: {
      source: PropTypes.any.isRequired,
      imageSize: PropTypes.shape({
        width: PropTypes.number.isRequired,
        height: PropTypes.number.isRequired,
      })

...
```

lib/Image.js (clearly compiled from `src`):

```
var _react = require("react");

...

propTypes: {
    source: _react.PropTypes.any.isRequired,
    imageSize: _react.PropTypes.shape({
      width: _react.PropTypes.number.isRequired,
      height: _react.PropTypes.number.isRequired
    }),
```

gl-react-image/package.json:

```
{
        "name": "gl-react-image",
        "version": "0.0.2",
        ...
}

```

This is what I'm referring to, and is 100%  able to be replicated by following the steps above. The issue is in `React.PropTypes` being deprecated in ~RN 48 or 49. To fix, `gl-react-image/package.json` needs:

```
"peerDependencies": {
    ...,
    "prop-types": "^15.6.0"
}
```

Then `src/Image.js` needs `import PropTypes from "prop-types";` and all its `React.PropTypes` changed to `PropTypes`. After that, compile to create an updated `lib/Image.js` file.

**Comment by stoffern** [comment] 2017-12-09 11:25
semantic release is broken so thats why there is no new NPM releases and the `gl-react-image` dep is outdated. will fix it today

**Comment by stoffern** [comment] 2017-12-09 12:42
should be fixed there when semantic releases new version bb24ac9b3b90d9f414a87f166eb48db4f11bcc9a

**Closed by stoffern** 2017-12-09 12:42 UTC

**Comment by wmcbain** [comment] 2017-12-11 15:22
Sorry for joining in here late. Posted this and came down with a cold!

**Comment by stoffern** [comment] 2017-12-12 07:51
new release out:
https://github.com/stoffern/react-native-image-cropper/releases

**Comment by leuxcid** [comment] 2017-12-14 18:32
@wkoutre would we be able to fork gl react image 0.0.2 and make those changes to PropTypes  for react native image cropper?

**Comment by wkoutre** [comment] 2018-01-13 06:36
@leuxcid Sorry, missed this. Not sure, but it seems to be reconciled with the latest updates to RNIC.
